### ISSUE TITLE
License Issue

### ISSUE THREAD

**Issue by My-Name-Is-Jeff** [Nat3z/SkyTweaks#2]
Hey there! I'm a member of the Skytils organization. The SkytilsMod project is licensed under the terms of the GNU Affero General Public License 3.0, which states that for modifications: 

You must license the entire work, as a whole, under this
    License to anyone who comes into possession of a copy.  This
    License will therefore apply, along with any applicable section 7
    additional terms, to the whole of the work, and all its parts,
    regardless of how they are packaged.  This License gives no
    permission to license the work in any other way, but it does not
    invalidate such permission if you have separately received it.

**Comment by Nat3z** [comment]
Hello My-Name-Is-Jeff. After review of the license's terms, you are indeed correct. This mod (SkyTweaks) is indeed breaking the license terms of your mod (Skytils). I will make the appropriate changes as a result. Thank you for notifying me about these issues, I'm very sorry if anything bad has came as a result. If there are any other issues regarding licensing found in the mod, please reply to this issue. Thanks!
